#ifndef __SEXYAPPFRAMEWORK_UIENUMS_H__
#define __SEXYAPPFRAMEWORK_UIENUMS_H__

namespace Sexy
{
	enum GestureFlickDirection
	{
		GESTURE_FLICK_DIRECTION_INVALID	= -1,
		GESTURE_FLICK_DIRECTION_UP		= 0,
		GESTURE_FLICK_DIRECTION_DOWN,
		GESTURE_FLICK_DIRECTION_LEFT,
		GESTURE_FLICK_DIRECTION_RIGHT,
	};

} // Sexy namespace
	

#endif // __SEXYAPPFRAMEWORK_UIENUMS_H__
