#ifndef XBOX360_ERRORS_H_INCLUDED
#define XBOX360_ERRORS_H_INCLUDED

#define MODAL_RETRY_DIALOG_ID 0xFFFFF00D

enum Xbox360ErrorCode
{
	ERROR_PROFILE_READ,
	ERROR_PROFILE_WRITE,
	ERROR_PROFILE_DEVICE_FULL,
	ERROR_STORAGE_DEVICE_SELECTION,
	ERROR_STORAGE_DEVICE_REMOVED,
	ERROR_STORAGE_DEVICE_FULL,
	ERROR_STORAGE_DEVICE_LOW_MEM,
	ERROR_STORAGE_DEVICE_OVERWRITE,
	ERROR_STORAGE_DEVICE_OVERWRITE_CORRUPT,
	ERROR_SAVING_GAMESAVE,
	ERROR_LOADING_GAMESAVE,
	ERROR_DELETING_GAMESAVE,
	ERROR_CONFIRM_OVERWRITE,
	ERROR_LEADERBOARD_WRITE
};

#define ERROR_TITLE(code) gSexyAppBase->GetString("XBOX_"#code"_TITLE",StrFormat(L"%S","XBOX_"#code"_TITLE"))
#define ERROR_TEXT(code) gSexyAppBase->GetString("XBOX_"#code,StrFormat(L"%S","XBOX_"#code))
#define ERROR_FOOTER(code) gSexyAppBase->GetString("XBOX_"#code"_FOOTER",StrFormat(L"%S","XBOX_"#code"_FOOTER"))

#endif
