//
//  PrimeGlyphMesh.h
//  SexyAppFramework Prime
//
//  Created by Jason Emery on 4/5/13.
//
//

#ifndef __SexyAppFramework_Prime__PrimeGlyphMesh__
#define __SexyAppFramework_Prime__PrimeGlyphMesh__

#include "Prime_EATech_Bridge.h"
#include "Graphics.h"

namespace Sexy
{

////////////////////////////////////////////////////////////////////////////////
/// Draws a mesh representing text glyphs using EA::Graphics GL context.
////////////////////////////////////////////////////////////////////////////////
class PrimeGlyphMesh
{
public:
    /// Constructor.
    PrimeGlyphMesh();
    
    /// Destructor.
    ~PrimeGlyphMesh();
    
    /// Initializes the class for use. This function should be called after any
    /// setup Set functions (e.g. SetDevice) but before rendering functions (Build/Draw).
    ///
    /// @param glyphCache   The object used to build the glyph cache.
    bool Init(EA::Allocator::ICoreAllocator* allocator, EA::Text::GlyphCache* glyphCache);
    
    void SetMVPMatrix(float left, float right, float top, float bottom);
    void SetMVPMatrix(float *mat);
    
    /// Releases any resources acquired during usage.
    bool Shutdown();
    
    /// Reserve space for a mesh of at least glyphCapacity glyphs.
    /// This function is rather like the STL vector::reserve function.
    /// This function is mostly useful for the case whereby you plan on
    /// re-using a GlyphMesh to redraw text as you go.
    /// This function can be called at any time but would typically be
    /// called just a single time before Init.
    /// Beware that the required glyph count may be greater than the
    /// text character count, especially with some complex languages.
    bool Reserve(uint32_t glyphCapacity);
    
    /// Sets the LineLayout to be used by the Build() and Draw() functions. A
    /// LineLayout is generated by EATextTypesetter and it is the fundamental
    /// unit of text layout.
    void SetLineLayout(EA::Text::LineLayout* pLineLayout);
    
    /// Specifies how color is chosen for glyph vertex coloring.
    /// The glyphs can be colored by one of two means: the color stored in the
    /// LineLayout.mAnalysisInfoArray[].mpTextStyle per character or the color
    /// specified by the SetColor function in this class. The former is more powerful
    /// and useful for advanced layout but is a little slower to process and
    /// requires that the LineLayout be done via EAText TextStyles.
    /// By default the second method (this class' SetColor) is used, but the user
    /// can use this function to change that.
    void SetTextStyleColorEnabled(bool enabled);
    
    /// Sets the RGBA color to draw the glyphs.
    /// This function can be called at any time, and it can be used to vary
    /// the color of text within a drawn LineLayout.
    void SetColorRGBA(uint32_t color);
    
    /// Sets the ARGB color to draw the glyphs. (0xAARRGGBB like EAText)
    /// This function can be called at any time, and it can be used to vary
    /// the color of text within a drawn LineLayout.
    /// Deprecated: Please use SetColorRGBA().
    EA_PREFIX_DEPRECATED void SetColor(uint32_t color);
    
    /// Enables or disable the clipping.
    void SetClippingEnabled(bool enabled);
    
    /// Checks if the clipping is enabled.
    bool IsClippingEnabled() const;
    
    /// Sets a rectangle to clip output to during the Build function.
    /// Clipping is done at the polygon level and not the glyph level.
    /// Thus if a glyph is partially clipped then it will be partially
    /// drawn, as opposed to the entire glyph being omitted.
    /// Clipping is applied during Build, so if you want to change the
    /// clipping then you need to call Build again.
    /// The build rectangle coordinate space is the LineLayout coordinate
    /// space (i.e. model coordinate space) as opposed to world or screen
    /// coordinate space. To apply a world or screen coordinate space
    /// clipping, you need to accomplish this via GPU-level functionality
    /// such as the depth, stencil, or screen alpha testing or via a
    /// vertex or fragment GPU program.
    void SetClippingRect(float left, float top, float right, float bottom);
    
    /// Builds a mesh based on the current settings (LineLayout, color).
    /// The Build operation doesn't apply color; color is applied during the
    /// Draw operation or via shader parameters the user may have set.
    /// This function need only be called once for a given layout, but
    /// it is safe (though inefficient) to be called multiple times.
    /// Calling Build has the same effect as BuildBegin(), BuildPart(), BuildEnd().
    void Build(float fYScale = 1.0f);
    
    /// Begin an incremental build. This is an alternative to Build().
    /// Must be eventually followed by a BuildEnd call after any number of
    /// BuildPart calls.
    /// glyphCount is the number of glyphs that will be built.
    /// This function is useful for creating a single mesh that uses multiple
    /// LineLayouts and/or colors.
    /// glyphIndexEnd follows the 'iterator' standard of being one-past the
    /// last valid index.
    bool BuildBegin(uint32_t glyphCount = 0xffffffff);
    
    /// Add a part of the current LineLayout to an incremental build.
    bool BuildPart(float fYScale = 1.0f, uint32_t glyphIndexBegin = 0, uint32_t glyphIndexEnd = 0xffffffff);
    
    /// Finalizes a build begun with BuildBegin.
    void BuildEnd();
    
    
    /// Draw the text that was most recently built to the currently set device.
    /// It is expected that the Build function be called prior to this Draw function.
    /// It is expected that the lineLayout be the same one used with the Build function.
    /// Note that a given glyphIndex may not match the same characterIndex. You need
    /// to use LineLayout::GetGlyphRangeFromCharRange to properly get a glyph range
    /// from a char range. The user is required to do this instead of the function
    /// doing this because the user may want to throw away the LineLayout before
    /// calling this function.
    void Draw(Sexy::Graphics* g, uint32_t glyphIndexBegin = 0, uint32_t glyphIndexEnd = 0xffffffff);
    
    /// Adds a post scaling to the text, attempting to keep it centered.
    /// This results in pixelated text as the glyphs are scaled after being generated.
    /// To do this it needs knowledge of the original extents, which so far I don't know how to
    /// calculate from the LineLayout struct.
    void SetPostScale(float scaleX, float scaleY, float originX, float originY, float width, float height);
    
#ifdef DEBUG_PRIMETEXT
    void SetTextWasAutofit(bool wasAutofit) { mTextWasAutofit = wasAutofit; }
    bool WasTextAutofit() { return mTextWasAutofit; }
    void SetTextExtents(Rect extents) { mTextExtents = extents; mTextHasExtents = true; }
#endif
    
protected:
    //Save the current state that glyphmesh need to change to draw
    void SaveStates();
    
    //Restore the state glyphmesh changed
    void RestoreStates();
    
    /// Drawing
    void Draw_Characters(Sexy::Graphics* g, int32 textureIndex, bool isLastTexture);
    void Draw_DebugCharacterRects(Sexy::Graphics* g, Sexy::SexyVertex2D firstVertex[][3], int32 triangleCount);
    void Draw_CharacterTriangles(Sexy::Graphics* g, Sexy::Image* image, Sexy::SexyVertex2D firstVertex[][3], int32_t triangleCount);

    SexyMatrix3 CalculateScaleTransform(float startOffsetX, float startOffsetY);
    
    void AllocateSexyVerts(int glyphCount);
    void ClearSexyVerts();
    
    /// Defines a vector of float.
    typedef eastl::vector<float, EA::Allocator::EASTLICoreAllocator> FloatVector;
    
    /// Defines a vector of colors. (uint32_t)
    typedef eastl::vector<uint32_t, EA::Allocator::EASTLICoreAllocator> ColorVector;
    
    /// Defines a vector of texture ID. (uint32_t)
    struct TextureUsageInfo
    {
        Sexy::DeviceImage*	mImage;
        int32_t		mTriangleFirst;
        bool		mIsVertexColorConstant;
    };
    typedef eastl::vector<TextureUsageInfo, EA::Allocator::EASTLICoreAllocator> TextureVector;
    
    /// The memory allocator used by the mesh.
    EA::Allocator::ICoreAllocator* mAllocator;
    
    /// The object used by EAText to create/update the GL texture containing the cached glyph.
    EA::Text::GlyphCache* mGlyphCache;
    
    /// The texture info containing information about glyphes.
    EA::Text::TextureInfo* mCacheTextureInfo;
    
    /// The line layout to build and render.
    EA::Text::LineLayout* mLineLayout;
    
    /// The mesh color. It will be the color of the font if mTextStyleColorEnabled == false.
    uint32_t mColor;
    
    /// If the flag is true, characters will have the color specified by LineLayout.mAnalysisInfoArray[].mpTextStyle.
    bool mTextStyleColorEnabled;
    
    /// Indicates if the clipping is enabled.
    bool mClippingEnabled;
    
    /// Clipping coordinates.
    float mClipLeft;
    float mClipTop;
    float mClipRight;
    float mClipBottom;
    
    typedef Sexy::SexyVertex2D SexyVertex_Triangle[3];
    
    /// Contains vertex information to display textures
    SexyVertex_Triangle* mTriangles;
    SexyVertex_Triangle* mTrianglesTmp;
    int mTrianglesNum;
    int mTrianglesUsed;
    
    /// Contains texture information for every quad (2 triangles).
    TextureVector mTextures;
    
    /// Model view matrix projection
    float mMVP[16];
    bool  mIsMVPDirty;
    bool  mIsUsedMVPFlag;
    // Post-Build Scaling values
    bool  mScaleToApply;
    float mScaleOriginX;
    float mScaleOriginY;
    float mScaleX;
    float mScaleY;
    float mScaleWidth;
    float mScaleHeight;

    // Debugging
#ifdef DEBUG_PRIMETEXT
private:
    /// If this text was altered by the text autofit
    bool mTextWasAutofit;
    Rect mTextExtents;
    bool mTextHasExtents;
    void DrawDebugTextRect(Graphics* g);
#endif
    
};

}   // namespace Sexy

#endif /* defined(__SexyAppFramework_Prime__PrimeGlyphMesh__) */
