//
//  MessageWidgetEnums.h
//  PlantsVersusZombies2
//
//  Created by Austin McGee on 12/12/12.
//  Copyright (c) 2012 PopCap Games. All rights reserved.
//

#ifndef PlantsVersusZombies2_MessageWidgetEnums_h
#define PlantsVersusZombies2_MessageWidgetEnums_h

//
// Message "Style" - the style determines the duration, fade and color of the text.
//
enum MessageStyle
{
	MESSAGE_STYLE_OFF,
	MESSAGE_STYLE_TUTORIAL_LEVEL1,
	MESSAGE_STYLE_TUTORIAL_LEVEL1_STAY,
	MESSAGE_STYLE_TUTORIAL_LEVEL2,
	MESSAGE_STYLE_TUTORIAL_LATER,
	MESSAGE_STYLE_TUTORIAL_LATER_STAY,
	MESSAGE_STYLE_HINT_LONG,
	MESSAGE_STYLE_HINT_FAST,
	MESSAGE_STYLE_HINT_STAY,
	MESSAGE_STYLE_HINT_TALL_FAST,
	MESSAGE_STYLE_HINT_TALL_STAY,
	MESSAGE_STYLE_HINT_TALL_UNLOCKMESSAGE,
	MESSAGE_STYLE_HINT_TALL_LONG,
	MESSAGE_STYLE_BIG_MIDDLE,
	MESSAGE_STYLE_BIG_MIDDLE_FAST,
    MESSAGE_STYLE_BIG_MIDDLE_STAY,
	MESSAGE_STYLE_HOUSE_NAME,
	MESSAGE_STYLE_HUGE_WAVE,
	MESSAGE_STYLE_SLOT_MACHINE,
	MESSAGE_STYLE_ZEN_GARDEN_LONG,
	
	MESSAGE_STYLE_WORLDMAP_WINNI,
	MESSAGE_STYLE_WORLDMAP_WINNI_STAY,
	
	MESSAGE_STYLE_READYSETPLANT,
	MESSAGE_STYLE_READYSETPLANT_FINAL,
	MESSAGE_STYLE_FINAL_WAVE,
	
	MESSAGE_DISABLED_PAM_TEXT,
    
    MESSAGE_STYLE_SNAKE_ADD,
    MESSAGE_STYLE_SNAKE_SLOW,
    MESSAGE_STYLE_PERK_ACTIVATED,

    MESSAGE_STYLE_CARD_GAME_HINT_STAY,
};

#endif
