/*****************************\
 * Copyright © 2008 - 2011   *
 * Electronic Arts           *
 * Version 12.3.1.0          *
\*****************************/

#ifndef _IPSP_CONSTANTS_H_
	#define _IPSP_CONSTANTS_H_

enum {
	ERR_CORE_MASTER_ITEM_NOT_FOUND			= -10001,
	ERR_CORE_USER_NOT_FOUND					= -10002,
	ERR_CORE_USER_NOT_GRANTED				= -10003,
	ERR_CORE_DEVICE_NOT_GRANTED				= -10004,
	ERR_CORE_USER_MUST_UPGRADE_APP			= -10005,
	ERR_CORE_ITEM_NOT_FOUND					= -10006,
	ERR_CORE_MASTER_ITEM_NOT_FOUND_FOR_LANG	= -10007,
	
	ERR_DRM_REQUIRED_PARAMETER_MISSING		= -2,
	ERR_DRMC_USER_NOT_FOUND					= -30001,
	ERR_DRM_ITEM_NOT_FOUND					= -30002,
	ERR_DRM_ITEM_NOT_PURCHASED				= -30004,
	ERR_DRM_DEVICE_DOWNLOAD_LIMIT_EXCEEDED	= -30005,
	ERR_DRM_ACCOUNT_BLOCKED					= -30006,
	ERR_DRM_NORECORD_ORIGINAL_PURCHASE		= -30007,
	ERR_DRM_RESTORE_LIMIT_EXCEEDED			= -30008,
	ERR_DRM_TRANSACTION_IS_INVALID			= -30009,
	ERR_DRM_INVALID_UID						= -30010,
	ERR_DRM_INVALID_TRANSACTIONID			= -30011,
	ERR_DRM_UID_SHOULD_BE_A_NUMBER			= -30012,
	ERR_DRM_NONCE_IS_NOT_VALID				= -30013,
	ERR_DRM_SIGNATURE_IS_NOT_VALID			= -30014,
	ERR_DRMI_USER_NOT_FOUND					= -31001,
	ERR_DRM_NO_ITEM_FOR_SELLID				= -31002,
	ERR_DRM_ERROR_VALIDATING_RECEIPT		= -31003,
	ERR_DRM_RECEIPT_FAILED_VERIFICATION		= -31004,
	
	ERR_TRACK_SHARD_UNABLE_TO_CHECK_STATUS	= -1,
	ERR_TRACK_USER_NOT_FOUND				= -40001,
	ERR_TRACK_NO_ITEM_FOR_SELLID			= -40002,
	ERR_TRACK_INVALID_EVENTID				= -40003,
	ERR_TRACK_INVALID_TIMESTAMP				= -40004,
	ERR_TRACK_LOG_EVENT_FAILED				= -40005,
	ERR_TRACK_WRITTEN_EVENT_NOT_FOUND		= -40006,
	ERR_TRACK_TRACKING_DISABLED				= -40010,
	ERR_TRACK_NO_USER_GAMEDATA				= -40011,
	ERR_TRACK_INVALID_VERSION_FORMAT		= -40012,
	ERR_TRACK_CANNOT_RETRIEVE				= -40013,
	ERR_TRACK_VERSION_OUTDATED				= -40014,
	ERR_TRACK_INVALID_PRODUCT_OR_USER		= -40015,
	ERR_TRACK_SHARD_IS_NOT_AVAILABLE		= -40020,
		
	ERR_M2U_CORE_USER_NOT_FOUND				= -50001,
	ERR_M2U_CORE_ITEM_NOT_FOUND				= -50002,
	ERR_M2U_CORE_NO_BANNERS_AVAILABLE		= -50003,
	ERR_M2U_CORE_NO_TICKERS_AVAILABLE		= -50004,
	ERR_M2U_CORE_NO_NEW_MESSAGES			= -50005,
	
	ERR_M2U_CORE_UNKNONW_OR_INTERNAL_ERROR	= -1,
	ERR_M2U_IPHONE_USER_NOT_FOUND			= -51001,
	ERR_M2U_CORE_INVALID_TOKEN				= -51002,
	ERR_M2U_CORE_USER_NOTOPTED_MESSAGES		= -51003,
	ERR_M2U_CORE_TEMPLATE_NOT_FOUND			= -51004,
	ERR_M2U_CORE_FEEDS_NO_MESSAGES_FOUND	= -51005,
	ERR_M2U_CORE_FEEDS_NO_NEW_MESSAGES		= -51010,
	ERR_M2U_CORE_OPTIONAL_REGISTRATION_FIELDS_NOT_FOUND	= -51011,
	ERR_M2U_CORE_LOGO_MESSAGES_NOT_FOUND	= -51012,
	
	ERR_M2U_CORE_PUSH_TOKEN_NOT_FOUND		= -51005,
	ERR_M2U_CORE_INVALID_PUSH_CERTIFICATE	= -51006,
	ERR_M2U_CORE_PUSH_CERTIFICATE_EXPIRED	= -51008,
	
	ERR_M2U_ANDROID_INVALID_REGISTRATION_ID	= -51002,
	ERR_M2U_ANDROID_USER_NOT_REGISTERED_TO_RECEIVE_PN = -51003,
	
	ERR_DIRECTOR_INVALID_BUNDLE_ID			= -70001,
	ERR_DIRECTOR_SERVERS_ARE_FULL			= -70002,
	
	ERR_INVALID_EAMOBILEID					= -3000,
	
	ERR_REQUEST_CANCELLED					= -1111,
	ERR_PURCHASE_CANCELLED					= -3333,
	ERR_PURCHASE_UNKNOWN					= -4444,
	ERR_RESTORE_CANCELLED					= -5555,
	ERR_RESTORE_UNKNOWN						= -6666,
	ERR_PURCHASE_LOWVERSION					= -7777,
	ERR_INSUFF_SPACE						= -8888,
	ERR_DOWNLOAD_URL_NOT_FOUND				= -9999,
	ERR_INVALID_OWNER						= -2000,
	
	//Social Errors
	ERR_SERVER_UNAVAILABLE					= -1000,
	ERR_USER_NOT_LOGGED_IN					= -1001,
	ERR_USER_NOT_ALLOWED					= -1002,
	ERR_FBCONNECT_ERROR						= -1003,
	ERR_AUTHORIZATION_ERROR					= -1004,
	ERR_INVALID_URI							= -1005,
	ERR_USER_NOT_FOUND						= -1006,
	
	// IPSP Defined Errors
	ERR_AVATAR_GALLERY_NOT_FOUND					= -1007,
	ERR_GOOGLECONNECT_ERROR							= -1008,
	ERR_ENCRYPTED_TOKEN_NOT_FOUND					= -1009,
	ERR_ERROR_GETTING_EAMOBILE_UID					= -1010,
	ERR_COUNTRY_CODE_INVALID						= -1011,
	ERR_ORIGIN_IS_DISABLED							= -1012,
    ERR_ORIGIN_LOGIN_DISABLED                       = -1013,
	ERR_IPSP_REQUIRED_PARAMETER_MISSING				= -1014,
	ERR_IPSP_UNEXPECTED_RESPONSE_FORMAT				= -1015,
	
	// Origin/Nucleus Errors, returned under key "errorCode".
	ERR_USER_UNKNOWN_OR_INTERNAL_ERROR			= -1,
	ERR_USER_INVALID_EMAIL_ADDRESS				= -20004,
	ERR_USER_NO_UDID_LINKED_TO_ACCOUNT			= -20008,
	ERR_USER_UID_SHOULD_BE_A_NUMBER				= -20009,
	ERR_USER_ALREADY_HAS_EAID					= -20010,
	ERR_USER_REGISTRATION_FAILED				= -20015,
	ERR_USER_UNEXPECTED_HTTP_CODE				= -20016,
	ERR_USER_LOGIN_FAILED						= -20017,
	ERR_USER_UNEXPECTED_FORMAT					= -20018,
	ERR_USER_USERNAME_SEARCH_FAILED				= -20019,
	ERR_USER_PERSONA_CREATION_FAILED			= -20020,
	ERR_USER_PERSONA_LISTING_FAILED				= -20021,
	ERR_USER_PERSONA_NOT_FOUND					= -20022,
	ERR_USER_BECS_SERVICE_FAILURE				= -20023,
	ERR_USER_BECS_USER_NOT_FOUND				= -20024,
	ERR_USER_TOS_NOT_FOUND						= -20026,
	ERR_USER_TOS_SERVICE_FAILURE				= -20027,
	ERR_USER_USER_REFERENCE_CREATION_FAILED		= -20031,
	ERR_USER_FACEBOOK_VALIDATION_FAILED_FOR_DISCOVERABLE = -20031,
	ERR_USER_FAILED_TO_RETRIEVE_AGE_LIMIT		= -20032,
	ERR_USER_USER_API_FAILURE					= -20033,
	ERR_USER_AUTH_TOKEN_CREATION_FAILED			= -20034,
	ERR_USER_REFERENCE_NOT_FOUND				= -20035,
	ERR_USER_AUTH_TOKEN_VALIDATION_FAILED		= -20036,	
	ERR_USER_CORE_USER_INFO_FAILED				= -20037,	
	ERR_USER_SEARCH_STRING_TOOSHORT				= -20038,
	ERR_USER_PRIVACY_DOCUMENT_NOT_FOUND			= -20039,
	ERR_USER_LICENSE_DOCUMENT_NOT_FOUND			= -20040,
	ERR_USER_INVALID_DOCUMENT_TYPE				= -20041,
	ERR_USER_INVALID_LANGUAGE_CODE				= -20042,
	ERR_USER_INVALID_DATE_OF_BIRTH				= -20043,
	ERR_USER_ENCRYPTED_TOKEN_VALIDATION_FAILED	= -20044,
	ERR_USER_INVALID_EMAIL_FORMAT				= -20045,
	ERR_USER_EMAIL_NOT_REGISTERED				= -20046,
	ERR_USER_USERNAME_REQUIRED					= -20048,
	ERR_USER_DUPLICATE_USERNAME					= -20049,
	ERR_USER_USERNAME_TOO_SHORT					= -20050,
	ERR_USER_USERNAME_TOO_LONG					= -20051,
	ERR_USER_USERNAME_NOT_ALLOWED				= -20052,
	ERR_USER_EMAIL_INVALID						= -20053,
	ERR_USER_EMAIL_DOMAIN_INVALID				= -20054,
	ERR_USER_EMAIL_REQUIRED						= -20055,
	ERR_USER_DUPLICATE_EMAIL					= -20056,
	ERR_USER_EMAIL_TOO_LONG						= -20057,
	ERR_USER_PASSWORD_REQUIRED					= -20058,
	ERR_USER_PASSWORD_TOO_SHORT					= -20059,
	ERR_USER_PASSWORD_TOO_LONG					= -20060,
	ERR_USER_PASSWORD_INVALID					= -20061,
	ERR_USER_PASSWORD_CONTAINS_SPACES			= -20062,
	ERR_USER_DUPLICATE_PASSWORD_AND_EMAIL_COMBO	= -20063,
	ERR_USER_DATE_OF_BIRTH_REQUIRED				= -20064,
	ERR_USER_DATE_OF_BIRTH_INVALID				= -20065,
	ERR_USER_DATE_OF_BIRTH_TOO_YOUNG			= -20066,
	ERR_USER_DATE_OF_BIRTH_TOO_OLD				= -20067,
	ERR_USER_TERMS_OF_SERVICE_REQUIRED			= -20068,
	ERR_USER_TERMS_OF_SERVICE_TOO_LONG			= -20069,
	ERR_USER_CONNECTION_TIMEOUT					= -20072,
	ERR_USER_COUNTRY_MISSING					= -20073,
	ERR_USER_COUNTRY_INVALID					= -20074,
	ERR_USER_COUNTRY_BANNED						= -20075,
	ERR_USER_LANGUAGE_MISSING					= -20076,
	ERR_USER_LANGUAGE_INVALID					= -20077,
	ERR_USER_LOCALE_INVALID						= -20078,
	ERR_USER_LOCALE_LANGUAGE_INVALID			= -20079,
	ERR_USER_LOCALE_COUNTRY_INVALID				= -20080,
	ERR_USER_LOCALE_LANGUAGE_CONFLICT			= -20081,
	ERR_USER_PROFILE_UPDATE_FAILED				= -20082,
	ERR_USER_REQUIRED_PARAMETERS_MISSING		= -20082,
	ERR_USER_UID_MISSING						= -20083,
	ERR_USER_IS_UNAUTHORIZED					= -20084,
	ERR_USER_REALNAME_TOO_LONG					= -20086,
	ERR_USER_TOO_MANY_ATTEMPTS					= -20090,
	ERR_USER_EADEVICEID_VALIDATION_FAILED		= -20093,
	ERR_USER_CLEAR_CLIENT_CACHED_EADEVICEID		= -20094,
	ERR_USER_USER_NOT_FOUND						= -21002,

	ERR_ORIGIN_USER_NOT_LOGGED_IN				= -21003,
};

// These are errors returned in certain Nucleus events, in the resultDictionary, under the key "error".
// These are related to EBISU server calls
enum 
{
	ERR_ORIGIN_ACCOUNT_DOES_NOT_EXIST					= 901,
	ERR_ORIGIN_HTTP_REQUEST_PARAMETER_MISMATCH			= 909,

	ERR_ORIGIN_EMPTY_NUCLEUS_AND_PERSONA_IDS			= 20006,
	ERR_ORIGIN_FRIEND_ID_IS_EMPTY						= 20007,
	ERR_ORIGIN_CURRENT_PRIVACY_NOT_SUPPORTED			= 20008,

	ERR_ORIGIN_USERS_FRIENDS_COUNT_LIMIT_EXCEEDED		= 22001,
	ERR_ORIGIN_NUCLEUS_AUTH_TOKEN_INVALID				= 22004,
	ERR_ORIGIN_AUTH_TOKEN_AND_NUCLEUS_ID_INCONSISTENT	= 22005,
	ERR_ORIGIN_INVITER_NOT_IN_REQUEST_LIST				= 22006,
	ERR_ORIGIN_DELETEE_NOT_IN_FRIEND_LIST				= 22007,
	ERR_ORIGIN_DELETEE_EXISTS_IN_OTHER_GROUP			= 22008,
	ERR_ORIGIN_INVITER_IS_BLOCKED						= 22009,
	ERR_ORIGIN_INVITEE_EXISTS_AS_FRIEND					= 22010,
	ERR_ORIGIN_INVITEE_IS_BLOCKED						= 22011,
	ERR_ORIGIN_CANNOT_BLOCK_HIMSELF						= 22015,
	ERR_ORIGIN_CANNOT_INVITE_HIMSELF					= 22017,

	ERR_ORIGIN_LOGINREGISTRATION_API_ACCESS_ERROR		= 24001,
	ERR_ORIGIN_NUCLEUS_SERVER_ACCESS_ERROR				= 24002,

	ERR_ORIGIN_AVATARS_AUTHTOKEN_INVALID				= 10044,
	ERR_ORIGIN_AVATARS_GENERIC_NUCLEUS_ERROR			= 10053,
	ERR_ORIGIN_AVATARS_AUTHTOKEN_USERID_INCONSISTENT	= 10066,
	ERR_ORIGIN_AVATARS_INVALID_OR_EMPTY_PARAMETER		= 10098,
	ERR_ORIGIN_AVATARS_USERID_OR_AVATARID_INVALID		= 10098,
	ERR_ORIGIN_AVATARS_NO_AVATAR_WITH_AVATARID			= 10075,
	ERR_ORIGIN_AVATARS_AVATAR_UNAVAILABLE				= 10123,
};

enum{
	BANNER_MAINMENU			= 1,
	BANNER_MAINMENU_IPAD	= 1,
	BANNER_THUMBNAILS		= 2,
	BANNER_MYSTORE			= 3,
	BANNER_FEED				= 10,
	BANNER_MY_PROFILE		= 11,
	BANNER_FRIEND_PROFILE	= 12,	
};

enum{
	TICKER_MAINMENU			= 1,
	TICKER_MAINMENU_IPAD	= 1,
	TICKER_STORE			= 2,
	TYPE_IN_APP_MESSAGE_MAIN_MENU		= 4,
	TYPE_IN_APP_MESSAGE_MAIN_MENU_IPAD	= 4,
	
	// ORIGIN registration messages
	TYPE_ORIGIN_WELCOME_MESSAGE			= 10,
	TYPE_ORIGIN_SETUP_ACCOUNT_MESSAGE	= 11,
	TYPE_ORIGIN_DISABLED_MESSAGE		= 13,
};

typedef enum { //Changing this order will affect UI changes
	ORIGIN_LOGO_POSITION_TOP_LEFT		= 0,
	ORIGIN_LOGO_POSITION_TOP_RIGHT		= 1,
	ORIGIN_LOGO_POSITION_BOTTOM_RIGHT	= 2,
	ORIGIN_LOGO_POSITION_BOTTOM_LEFT	= 3,
	ORIGIN_LOGO_POSITION_CUSTOM			= 4,
} ORIGIN_LOGO_POSITION;

typedef enum {
	ORIGIN_UI_MODE_PORTRAIT				= 0,
	ORIGIN_UI_MODE_LANDSCAPE			= 1,
	ORIGIN_UI_MODE_IPAD					= 2,
	ORIGIN_UI_MODE_UNIVERSAL			= 3,
} ORIGIN_UI_MODE;

typedef enum {
	DEVICE_BUILD_TYPE_UNSPECIFIED		= 0,
	DEVICE_BUILD_TYPE_IPHONE			= 1,
	DEVICE_BUILD_TYPE_IPAD				= 2,
	DEVICE_BUILD_TYPE_UNIVERSAL			= 3
} DEVICE_BUILD_TYPE;

enum {
	PERIOD_DAY		= 0,
	PERIOD_WEEK		= 1,
	PERIOD_MONTH	= 2,
	PERIOD_ALLTIME	= 3,
	PERIOD_CUSTOM	= 4,
};

enum {
	FB_LOGIN_BUTTON_NORMAL,
	FB_LOGIN_BUTTON_WIDE
};

enum {
	FB_PERMISSION_PUBLISH_STREAM,
	FB_PERMISSION_OFFLINE_ACCESS,
};

typedef enum {
	GENDER_MALE,
	GENDER_FEMALE,
	GENDER_NOTSPECIFIED,
}MTX_Gender;

typedef enum {
	MTXBOOL_NOT_FETCHED,
	MTXBOOL_NO,
	MTXBOOL_YES
}MTX_BOOL;

typedef enum {
	FEEDSORTING_BY_ID,
	FEEDSORTING_BY_DATE
} MTX_FeedSorting;

typedef enum {
	FRIENDSOURCE_UNDEFINED,
	FRIENDSOURCE_NUCLEUS_MOBILE,
	FRIENDSOURCE_GOOGLE,
	FRIENDSOURCE_FACEBOOK
} MTX_FriendSource;


typedef enum {
	USERRELATION_UNKNOWN,
	USERRELATION_NO_ONE,
	USERRELATION_FRIENDS,
	USERRELATION_FRIENDS_OF_FRIENDS,
	USERRELATION_EVERYONE
} MTX_UserRelation;

typedef enum {
	CSISSUE_OFFENSIVE_CONTENT 		= 0x0001
} MTX_CustomerServiceIssue;

typedef enum
{
    eUNDEFINED = 0,
    eOrigin,
    eFacebook,
    eMayhem,
    eALL
} eUserType;

enum {
	REQUEST_METHOD_GET	= 0,
	REQUEST_METHOD_POST	= 1,
	REQUEST_METHOD_PUT	= 2,
};

enum {
	CREATE_ACCOUNT_SCREEN_ID	= 1,
	SETUP_ACCOUNT_SCREEN_ID		= 2,
};

typedef enum {
	IAC_CONFIG_UNSPECIFIED 	= -1,
	IAC_CONFIG_DL			= 0,
	IAC_CONFIG_UI			= 1
} IAC_Config;

typedef enum {
	ORIGIN_CONFIG_UNSPECIFIED 	= -1,
	ORIGIN_CONFIG_DL 			= 0,
	ORIGIN_CONFIG_UI			= 1
} ORIGIN_Config;

typedef enum {
    ORIGINBRIDGE_UIMODE_HIDDEN  = 0,
    ORIGINBRIDGE_UIMODE_LOGO    = 1,
    ORIGINBRIDGE_UIMODE_STRIP   = 2,
    ORIGINBRIDGE_UIMODE_EXPANDED = 3
} ORIGINBRIDGE_UIMODE;

typedef enum {
//  ORIGINBRIDGE_EXPANDED_PAGEID_UNSPECIFIED  = -1,
    ORIGINBRIDGE_EXPANDED_PAGEID_LOGIN        = 0,
    ORIGINBRIDGE_EXPANDED_PAGEID_FRIENDS      = 1,
    ORIGINBRIDGE_EXPANDED_PAGEID_REDEMPTION   = 2
} ORIGINBRIDGE_EXPANDED_PAGEID;

typedef enum {
	TARGETED_CROSS_PROMOTION_SPENDER = 0,
	TARGETED_CROSS_PROMOTION_ORIGIN = 1,
	TARGETED_CROSS_PROMOTION_FACEBOOK = 2,
} TARGETED_CROSS_PROMOTION_TAG;

typedef enum {
    APPVERSION_STATUS_OK                        = 0,
    APPVERSION_STATUS_UPDATE_RECOMMENDED        = 1,
    APPVERSION_STATUS_UPDATE_REQUIRED           = 2
} APPVERSION_STATUS;

typedef enum {
    DOWNLOAD_UNDEFINED      = -1,
    DOWNLOAD_MTX_ITEM       = 0,
    DOWNLOAD_GAME_ASSET		= 1,
    DOWNLOAD_DESC_PACK     = 2
} DOWNLOAD_TYPE;

enum {
	EVT_APPSTART_NORMALLY						= 10000,
	EVT_APPSTART_FROMPUSH						= 10001,
	EVT_APPSTART_AFTERINSTALL					= 10002,
	EVT_APPSTART_AFTERUPGRADE					= 10003,
	EVT_APP_SESSION_START						= 10004,
	
	EVT_APP_SESSION_TIME						= 10005,
//	EVT_APPSTART_FROM_EBISU						= 10006,
	
	EVT_APPSTART_FROM_URL						= 10009,
	EVT_APP_ENTER_FOREGROUND_FROM_URL			= 10010,
	
	EVT_APPEND_NORMALLY							= 20000,
	EVT_APPEND_ABNORMALLY						= 20001,

	//Do Not Use - Deprecated Event
	EVT_APP_INTERRUPTED							= 20002,
	EVT_APP_SESSION_END							= 20003,
	EVT_APP_ENTER_FOREGROUND_FROM_EBISU			= 20004,
	
	EVT_APP_SESSION_START_EMBED					= 20005,
	EVT_EMBED_OTD_UPGRADE						= 20006,
	
	EVT_OPT_FULL_PURCHASE						= 30000,
	EVT_MOREGAMES_ENTER							= 30001,
	EVT_MOREGAMES_CLICKTHROUGH					= 30002,
	EVT_MOREGAMES_GAMESELECT					= 30004,
	EVT_MOREGAMES_CATEGORYSELECT				= 30005,
	EVT_MOREGAMES_OVERLAY_APPEARS				= 30006,
	EVT_MOREGAMES_OVERLAY_BUYCLICK				= 30007,
	
	EVT_ENTER_FULL_GAME_OVERVIEW_SCREEN			= 30008,
	EVT_LITE_ED_GAME_DEMO_START					= 30009,
	EVT_LITE_ED_GAME_DEMO_END					= 30010,
	EVT_MAINMENU_BANNER_CLICK					= 30011,
	EVT_MAINMENU_TICKER_CLICK					= 30012,
	EVT_INSTORE_BANNER_CLICK					= 30013,
	EVT_INSTORE_TICKER_CLICK					= 30014,
	EVT_FEATURED_BANNER_CLICK					= 30015,
	EVT_MOREGAMES_CLICKTHROUGH_FEATURED			= 30017,
	EVT_MOREGAMES_CLICKTHROUGH_SIDEBANNER		= 30018,
	EVT_IPAD_UPSELL_MESSAGE_DISPLAYED			= 30019,
	EVT_IPAD_UPSELL_MESSAGE_NOTHANKS_CLICKED	= 30020,
	EVT_IPAD_UPSELL_MESSAGE_OK_CLICKED			= 30021,
	EVT_IPAD_UPSELL_MESSAGE_LATER_CLICKED		= 30022,
	EVT_UPSELL_VIDEO_CLICKED					= 30023,
	EVT_USER_TRACKING_OPTOUT					= 30024,
	
	EVT_GAMEPLAY_PROGRESSION_SPGAME_START		= 30025,	//SP = Single Player
	EVT_GAMEPLAY_PROGRESSION_SPGAME_RESTART		= 30026,
	EVT_GAMEPLAY_PROGRESSION_SPGAME_SAVE		= 30027,
	EVT_GAMEPLAY_PROGRESSION_SPGAME_CONTINUE	= 30028,
	EVT_GAMEPLAY_PROGRESSION_SPGAME_QUIT		= 30029,
	EVT_GAMEPLAY_PROGRESSION_SPGAME_COMPLETE	= 30030,
	EVT_GAMEPLAY_PROGRESSION_SPGAME_TIME_SPENT	= 30031,
	EVT_GAMEPLAY_PROGRESSION_SPGAME_SCORE		= 30032,
	
	EVT_GAMEPLAY_PROGRESSION_TUTORIAL_SKIP		= 30033,
	EVT_GAMEPLAY_PROGRESSION_TUTORIAL_COMPLETE	= 30034,
	EVT_GAMEPLAY_PROGRESSION_CUTSCENE_SKIP		= 30035,	//Cut Scene or Movie
	EVT_GAMEPLAY_PROGRESSION_CONTROLSCHEME_USED	= 30036,
	EVT_GAMEPLAY_PROGRESSION_CHARACTER			= 30037,	//Charcter or Team or Avatar

	EVT_GAMEPLAY_PROGRESSION_MPGAME_START		= 30038,	//MP = Multiplayer
	EVT_GAMEPLAY_PROGRESSION_MPGAME_QUIT		= 30039,
	EVT_GAMEPLAY_PROGRESSION_MPGAME_DISCONNECT	= 30040,
	EVT_GAMEPLAY_PROGRESSION_MPGAME_COMPLETE	= 30041,
	EVT_GAMEPLAY_PROGRESSION_MPGAME_TIME_SPENT	= 30042,
	
	EVT_MULTITASKING_USER_APP_MINIMIZED			= 30043,
	EVT_MULTITASKING_USER_APP_RESUMED			= 30044,
	EVT_MULTITASKING_USER_START_TUTORIAL		= 30045,
	
	EVT_MTXVIEW_ENTER							= 40000,
	EVT_MTXVIEW_GAMECATEGORY					= 40001,
	EVT_MTXVIEW_ITEMSELECT						= 40002,
	EVT_MTXVIEW_ITEMPURCHASE					= 40003,
	EVT_MTXVIEW_ENTER_FROMCTX					= 40004,
	EVT_MTXVIEW_FREEITEM_DOWNLOADED				= 40005,
	EVT_MTXVIEW_ITEM_PURCHASED					= 40006,
	EVT_IAC_MTX_ITEM_USED						= 40007,

	EVT_MTXVIEW_ITEM_PURCHASED_REFERRERDATA		= 40008,
	EVT_MTXVIEW_ITEMPURCHASE_SLOTDATA			= 40009,
	EVT_MTXVIEW_ITEDISPLAYED					= 40010,
	
	EVT_IGE_FREE_CREDITS_EARNED					= 40011,
	EVT_IGE_PAID_CREDITS_EARNED					= 40012,
	EVT_IGE_GIFT_RECEIVED						= 40013,
	EVT_IGE_GIFT_SENT							= 40014,
	EVT_IGE_FREE_CREDITS_ITEMS_CLICK			= 40015,
	EVT_IGE_PAID_CREDITS_ITEMS_CLICK			= 40016,
	EVT_IGE_STORE_VISIT							= 40017,
	EVT_IGE_PAID_CREDITS_PURCHASE_REVENUE		= 40018,
	EVT_IGE_PAID_CREDITS_PURCHASE_LEVEL			= 40019,
	EVT_IGE_FREE_CREDITS_PURCHASE_REVENUE		= 40020,
	EVT_IGE_FREE_CREDITS_PURCHASE_LEVEL			= 40021,
	EVT_IGE_GAME_START_CASH_DETAIL				= 40022,
	
	EVT_OFFERWALL_ITEM_REDEEMED_STORE_EAL		= 40023,
	EVT_OFFERWALL_ITEM_REDEEMED_USER_LEVEL_EAL	= 40024,
	EVT_OFFERWALL_ITEM_CLICK_EAL				= 40025,
	EVT_OFFERWALL_STORE_VISIT_EAL				= 40026,
	
	EVT_INGAME_AD_CLICK							= 40027,
	
	EVT_INGAME_LEVEL_FREE_CREDITS_COUNT			= 40028,
	EVT_INGAME_LEVEL_PAID_CREDITS_COUNT			= 40029,
	
	EVT_USER_LEVEL_MTX_ITEM_PURCHASED			= 40030,
	
	EVT_IGE_GAME_START_FREE_CREDIT				= 40031,
	EVT_IGE_GAME_START_PAID_CREDIT				= 40032,
	
	EVT_INGAME_EMAIL_OPEN						= 50001,
	EVT_INGAME_EMAIL_SEND						= 50002,
	EVT_INGAME_EMAIL_RECEIEVE					= 50003,

	//Do Not Use - Deprecated Event
	EVT_MEDIAPICKER_OPEN						= 50004,

	EVT_ACCESS_BT_MENU							= 50005,
	EVT_BEGIN_BT_SESSION						= 50006,
	EVT_COMPLETE_BT_SESSION						= 50007,
	EVT_ACCESS_WIFI_MENU						= 50008,
	EVT_BEGIN_WIFI_SESSION						= 50009,
	EVT_COMPLETE_WIFI_SESSION					= 50010,
	EVT_USR_ISSUE_PUSH_NOTIFICATION_CHALLENGE	= 50011,
	EVT_LANGUAGE_SELECTED						= 50012,
	
	//Do Not Use - Deprecated Event
	EVT_MENU_PROGRESSION_MAINMENU_SELECTED			= 50013,
	EVT_MENU_PROGRESSION_MAINMENU_SUBMENU_SELECTED	= 50014,

	//Do Not Use - Deprecated Event
	EVT_MENU_PROGRESSION_GAMEMENU_SELECTED			= 50015,
	EVT_MENU_PROGRESSION_GAMEMENU_SUBMENU_SELECTED	= 50016,
	
	EVT_DEVICE_ORIENTATION_CHANGED				= 50017,

	//Do Not Use - Deprecated Event
	EVT_ERROR_BLUETOOTH_WIFI_BOTH_ACTIVE		= 50018,
	

	EVT_ACCESS_INGAME_SCREEN					= 60001,
	EVT_LEAVE_INGAME_SCREEN						= 60002,
	EVT_USER_GAMEPLAY_FUNNEL_EAL				= 60003,
	EVT_USER_TUTORIAL_FUNNEL_EAL				= 60004,
	EVT_USER_TRANSACTION_FUNNEL					= 60005,
	EVT_USER_MESSAGING_FUNNEL					= 60006,
	EVT_USER_SIGNUP_FUNNEL						= 60007,
	
	EVT_USER_GAME_LOAD_FUNNEL					= 60008,
	EVT_USER_GAME_DOWNLOAD_FUNNEL				= 60009,	
	
	EVT_EVENTS_PURGED								= 70000,
	EVT_GP_LEVEL_PROMOTION_DAYS_TOTAL_EAL			= 70005,
	EVT_GP_LEVEL_PROMOTION_GAMEPLAY_TIME_TOTAL_EAL	= 70006,
	EVT_GP_ACHIEVEMENTS_CHECKPOINTS_EAL				= 70007,
	EVT_GP_XPGAIN_EVENT_EAL							= 70008,
	EVT_GP_EVENT_USER_EAL							= 70009,
	EVT_GP_APP_START_USER_LEVEL_EAL					= 70010,
	
	EVT_EBISU_EMAIL_PROMPT						= 80032,
	EVT_EBISU_PROMPT_INPUT						= 80033,
	EVT_EBISU_REGISTRATION_FUNNEL				= 80034,
	EVT_EBISU_OPTIONAL_REGISTRATION_FIELDS		= 80035,
	EVT_EBISU_REGISTRATION_ERROR				= 80036,
	EVT_EBISU_SIGNIN_FUNNEL						= 80037,
	EVT_EBISU_SIGNIN_ERROR						= 80038,
	EVT_EBISU_USER_SIGNIN						= 80039,
	EVT_EBISU_USER_FRIENDS_COUNT				= 80040,
	EVT_EBISU_ENTER_EBISUUI						= 80041,
	EVT_EBISU_FRIENDS_VISIT						= 80042,
	EVT_EBISU_FRIEND_SEARCH						= 80043,
	EVT_EBISU_FRIEND_INVITE_SENT				= 80044,
	EVT_EBISU_FRIEND_INVITE_ACCPTED				= 80045,	
	EVT_EBISU_NEWSFEED_VISIT					= 80046,
	EVT_EBISU_NEWSFEED_TILE_BUTTON_CLICK		= 80047,
	EVT_EBISU_NEWSFEED_BANNER_CLICK				= 80048,
	EVT_EBISU_NEWSFEED_UPDATES					= 80049,	
	EVT_EBISU_PROFILE_VISIT						= 80050,
	
	EVT_EBISU_LOGO_YES_CLICK					= 80051,
	EVT_EBISU_LOGO_NO_CLICK						= 80052,									
	EVT_EBISU_RECOVER_PASSWORD_FUNNEL			= 80053,	
	EVT_EBISU_USER_SIGNOUT						= 80054,
	EVT_EBISU_LOAD_FAIL							= 80055,
	EVT_EBISU_FRIEND_PROFILE_BANNER_CLICK		= 80056,	
	EVT_EBISU_FRIEND_PROFILE_GAME_ICON_CLICK	= 80057,
	EVT_EBISU_FRIEND_INVITE_REJECTED			= 80058,
	EVT_EBISU_PROFILE_BANNER_CLICK				= 80059,  
	
	EVT_EBISU_PROFILE_GAME_ICON_CLICK			= 80060,
	
	EVT_GAME_ERROR_CONNECTIVITY					= 90000,
	EVT_GAME_ERROR_GAMEPLAY						= 90001,	
};

enum {
	EVT_KEYTYPE_NONE			= 0,
	EVT_KEYTYPE_GAME_SELLID		= 1,
	EVT_KEYTYPE_MTX_SELLID		= 2,
	EVT_KEYTYPE_MTX_CATEGORY	= 3,
	EVT_KEYTYPE_SCREEN_NAME		= 4,
	EVT_KEYTYPE_EVENT_COUNT		= 5,
	EVT_KEYTYPE_DURATION		= 7,
	EVT_KEYTYPE_FREQUENCY		= 8,
	EVT_KEYTYPE_FEATURED		= 10,
	EVT_KEYTYPE_DMG_SECTION		= 11,
	EVT_KEYTYPE_GAME_PRODUCTID	= 12,
	EVT_KEYTYPE_DMG_CATEGORY	= 13,
	EVT_KEYTYPE_SCORE			= 14,
	EVT_KEYTYPE_ENUMERATION		= 15,	
	EVT_KEYTYPE_TICKERID		= 16,
	EVT_KEYTYPE_BANNERID		= 17,
	EVT_KEYTYPE_MESSAGEID		= 18,
	EVT_KEYTYPE_BANNER_POSITION = 19,
	EVT_KEYTYPE_LANGUAGE		= 20,
	EVT_KEYTYPE_USER_LEVEL_DATA	= 21,
	EVT_KEYTYPE_FIELD_ID		= 22,
	EVT_KEYTYPE_LOGO_MESSAGE_ID	= 23,
	EVT_KEYTYPE_FIELD_TYPE		= 24,
	EVT_KEYTYPE_LAST_EVENT		= 25,
};

typedef enum {
	ADTRACK_EVENT_APPSTARTED_AFTERINSTALL	= 101,
	ADTRACK_EVENT_APPSTARTED				= 102,
	ADTRACK_EVENT_APPRESUMED				= 103,
	ADTRACK_EVENT_USER_REGISTERED			= 104,
	ADTRACK_EVENT_MTXVIEW_ITEM_PURCHASED	= 105
}AdTrackingEventId;

typedef enum {
	DISABLE_UDID_FLAG_NONE			= 0,
	DISABLE_UDID_FLAG_UDID			= 1,
	DISABLE_UDID_FLAG_MACADDRESS	= 2,
	DISABLE_UDID_FLAG_RANDOMID		= 3,	
}DISABLE_UDID_FLAG;

// -- Event IDs	
typedef enum {
	Event_None = 0,
	Event_PostEventsDone,
	Event_PostEventsError,
	Event_RegisterTokenBegin,
	Event_RegisterTokenDone,
	Event_RegisterTokenError,
	Event_GetAvailableItemsBegin, 
	Event_GetAvailableItemsDone,
	Event_GetAvailableItemsError,
	Event_GetPurchasedItemsDone,
	Event_GetPurchasedItemsError,
	Event_DownloadItemBegin, 
	Event_DownloadItemDone,
	Event_DownloadItemError,
	Event_UnlockItem,
	Event_PurchaseItemBegin, 
	Event_PurchaseItemDone,
	Event_PurchaseItemError,
	Event_RestoreItemsBegin, 
	Event_RestoreItemsDone,
	Event_RestoreItemsError,
	Event_GetBannerDone,
	Event_GetBannerError,
	Event_GetBannersDone,
	Event_GetBannersError,
	Event_GetTickerDone,
	Event_GetTickerError,
	Event_GetMessageDone,
	Event_GetMessageError,
	Event_GetCategoriesDone,
	Event_GetCategoriesError,
	Event_GetStoreBadgesCountDone,
	Event_GetStoreBadgesCountError,
	Event_CleanUpError,
	Event_ServerError,
	Event_UnknownError,
	Event_DownloadAssetDone,
	Event_DownloadAssetError,
	Event_GetAppSellIdDone,
	Event_GetAppSellIdError,
	Event_GetUserFeedsDone,
	Event_GetUserFeedsError,
	Event_GetUserFeedsNoUpdate,
	Event_DidInstallAppDone,
	Event_DidInstallAppError,
	Event_IsFacebookEnabledDone,
	Event_IsFacebookEnabledError,
	Event_HandleInGameURL,
	Event_ServerUnavailable,
	Event_ServerURLsRetrieved,	
    Event_AppVersionOk,
    Event_AppVersionUpdateRecommended,
    Event_AppVersionUpdateRequired,
	Event_GetNucleusEntitlementDone,
	Event_GetNucleusEntitlementError,
	Event_PostNucleusEntitlementDone,
	Event_PostNucleusEntitlementError,
	 
	//Social Callbacks
	Event_GeneralError,	
	Event_SendPushNotificationDone,
	Event_SendPushNotificationError,	
	Event_CustomMayhemRequestDone,
	Event_CustomMayhemRequestError,	
	Event_AuthenticateMayhemDone,
	Event_AuthenticateMayhemError,	
	Event_MayhemServerError,

	//Identity	
	Event_GetMayhemIdsDone,
	Event_GetMayhemIdsError,
	Event_OriginServerError,
	Event_RenewMayhemTokenDone,
	Event_RenewMayhemTokenError,
	Event_DownloadDescPackDone,
	Event_DownloadDescPackError,
	
    Event_OriginBridgeInitializedDone,
    Event_OriginBridgeInitializedError,
    Event_OriginBridgeUIModeChanged,
    Event_OriginBridgeLoginStateChanged,
    
    Event_GetSynergyIdsDone,
	Event_GetSynergyIdsError,
    
	// DEPRECATED
	// These events have never been, or are no longer being sent to the game registered handler.
	Event_PublishFeedDone,
	Event_PublishFeedError,
	Event_PublishFeedCancelled,
	Event_GetFBLikeStateDone,
	Event_GetFBLikeStateError,
	Event_AskPermissionDone,
	Event_AskPermissionError,
	Event_AskPermissionCancelled,	
    Event_GetMessageTemplateDone,
	Event_GetMessageTemplateError,

	Event_PostChallengeDone,
	Event_PostChallengeError,
	Event_UpdateChallengeDone,
	Event_UpdateChallengeError,
	Event_GetChallengesDone,
	Event_GetChallengesError,
	Event_GetEAMobileIdDone,
	Event_GetEAMobileIdError,
	Event_GetAnonEAMobileIdDone,
	Event_GetAnonEAMobileIdError,
	Event_GetLatestEAMobileIdDone,
	Event_GetLatestEAMobileIdError,
	Event_AuthenticateOriginUserError,
	Event_AuthenticateOriginUserDone,
	Event_GetUserInfoError,
	Event_GetUserInfoDone,
	Event_GetLogoMessagesDone,
	Event_GetLogoMessagesError,
	Event_GetPendingSentInvitesDone,
	Event_GetPendingSentInvitesError,
	Event_GetPendingReceivedInvitesDone,
	Event_GetPendingReceivedInvitesError,	
	Event_GetEmailOptInStatusDone,
	Event_GetEmailOptInStatusError,
	Event_GetGamesOwnedDone,
	Event_GetGamesOwnedError,
	Event_GetGameInfoDone,
	Event_GetGameInfoError,
	Event_GetProfilePrivacyDone,
	Event_GetProfilePrivacyError,
    
    Event_MoreGamesExit,
	Event_StoreExit,
    Event_PostStoryDone,
	Event_PostStoryError,
	Event_DeleteStoryDone,
	Event_DeleteStoryError,
	Event_ClearFeedsDone,
	Event_ClearFeedsError,
    Event_SocialServerError,
	Event_FBLoginDone,
	Event_FBLoginError,
	Event_FBLogoutDone,
	Event_LoginCancelled,
	Event_FBLogoutError,
	Event_GetFBLoginButtonDone,
	Event_GetFBLoginButtonError,
	Event_FBDialogCancelled,
	Event_FBDialogFailedToLoad,
	Event_FBDialogWillAppear,
	Event_FBDialogWillDisappear,
	Event_GetFacebookFriendsDone,
	Event_GetFacebookFriendsError,
	Event_GetFriendsScoresDone,
	Event_GetFriendsScoresError,
	Event_PostScoreDone,
	Event_PostScoreError,
	Event_GetAchievementsDone,
	Event_GetAchievementsError,
	Event_AwardAchievementsDone,
	Event_AwardAchievementsError,
    Event_FBAccessTokenExpired,
    Event_SendChallengeDone,
	Event_SendChallengeError,
    Event_InviteFriendDone,
	Event_InviteFriendError,
	Event_GetFriendListError,
	Event_GetFriendListDone,
    Event_IsAppUserDone,
	Event_IsAppUserError,
	Event_GetAvatarsByUserIdsDone,
	Event_GetAvatarsByUserIdsError,
    Event_LogoutDone,
	Event_LogoutError,
	Event_RenewAuthTokenDone,
	Event_RenewAuthTokenError,			// Session expired, etc.
    Event_AutoLoginStarted,
	Event_AutoLoginDone,
	Event_AutoLoginDoneIdentityChanged,
	Event_AutoLoginError,
	Event_AutoLoginCanceled,
	Event_AnonymousLoginDone,
	Event_AnonymousLoginError,
    // Sent from OriginUI to game to notify of actions in the UI.
	Event_OriginUIWillAppear,			// Origin UI will maximize
	Event_OriginUIWillDisappear,		// Origin UI will minimize
	Event_OriginUIWillNotAppear,
	Event_OriginUIExit,					// Origin UI, including circular button, will no longer be displayed.
	Event_OriginUIError,
	Event_OriginGameAboutLinkPressed,
	Event_RegistrationComplete,			// Player finished Origin registration process.
	Event_UserLoggedIn,					// Player authenticated with Origin login process.
	Event_UserLoggedOut,				// Player has logged out.
	Event_OriginMessageWillAppear,
	Event_OriginMessageWillNotAppear,	// Origin message triggered, but the message is not available to display, has already been displayed, or another message is displayed.
	Event_OriginMessageWillDisappear,	// Active Origin message is going away.
	Event_FriendAddSent,
	Event_FriendAddAccepted,
	Event_FriendRemoved,
	Event_IAMWillAppear,
	Event_IAMWillDisappear,
	
	Event_ChallengeInitiated,		 	// includes initiatorUid, targetUid
	Event_ChallengeInitiatedError,
	Event_ChallengeAccepted, 			// includes initiatorUid, targetUid, and challenge metadata
	Event_ChallengeAcceptedError,
	
// #if NO_UDID_SOLUTION
	Event_ValidateDeviceIdDone,
	Event_ValidateDeviceIdError,
    Event_GetEADeviceIdDone,
    Event_GetEADeviceIdError,
// #endif
    
	// INTERNAL
#if defined IPSP_SDK_BUILD || defined IPSP_QA_TEST_BUILD_WITH_SOURCES
#include "Constants_Events_Internal.h"
#endif
	
} MTX_EventID;

enum IPSP_UI_Orientation {
    UI_Orientation_Unknown,
    UI_Orientation_Portrait,
    UI_Orientation_PortraitUpsideDown,
    UI_Orientation_LandscapeRight,
    UI_Orientation_LandscapeLeft
};

#define	CONNECTION_TYPE_3G		@"G"
#define	CONNECTION_TYPE_WIFI	@"W"
#define	CONNECTION_TYPE_NONE	@"N"

#define NEWS_FEED_CATEGORY_ORIGIN_PROMOTION		@"origin_promotion"
#define NEWS_FEED_CATEGORY_ORIGIN_SCORE			@"origin_score"
#define NEWS_FEED_CATEGORY_ORIGIN_ACHIEVEMENT	@"origin_achievement"
#define NEWS_FEED_CATEGORY_ORIGIN_CHALLENGE		@"origin_challenge"
#define NEWS_FEED_CATEGORY_ORIGIN_NEWS			@"origin_news"
#define NEWS_FEED_CATEGORY_ORIGIN_INFO			@"origin_info"
#define NEWS_FEED_CATEGORY_ORIGIN_GAMEPLAY		@"origin_gameplay"

//Defined landing point urls for logo messages 
#define	NEWS_FEED_UPDATES_LINK		@"eaorigin://feeds/updates"
#define	NEWS_FEED_INVITES_LINK		@"eaorigin://feeds/invites"
#define	FRIENDS_MY_FRIENDS_LINK		@"eaorigin://friends/myfriends"
#define	FRIENDS_ADD_FRIENDS_LINK	@"eaorigin://friends/addfriends"
#define	PROFILE_MY_PROFILE_LINK		@"eaorigin://profile/myprofile"
#define	PROFILE_SETTINGS_LINK		@"eaorigin://profile/settings"
#define	ORIGIN_LOGIN_LINK			@"eaorigin://login"

#define CHALLENGE_SEND_PUSH_TEMPLATE 		@"origin_push_challenge"
#define FRIEND_ACCEPT_PUSH_TEMPLATE 		@"origin_push_friendaccept"
#define	FRIEND_ADD_PUSH_TEMPLATE			@"origin_push_friendadd"

#define ORIGIN_LAUNCH_URL_SOURCE_APP_PRODUCT_ID_PARAM 	@"originLaunchSourceAppProdId"
#define ORIGIN_LAUNCH_URL_SOURCE_UI_PARAM				@"originLaunchSourceUI"
#define ORIGIN_LAUNCH_URL_PARAM							@"originLaunch"
#define ORIGIN_LAUNCH_URL_SOURCE_UI_PROFILE_PAGE		@"Profile_Page"
#define ORIGIN_LAUNCH_URL_SOURCE_UI_FRIENDS_PAGE		@"Friends_Page"
#define ORIGIN_LAUNCH_URL_SOURCE_UI_CHALLENGE_NEWSFEED	@"Challenge_NewsFeed"
#define ORIGIN_LAUNCH_URL_SOURCE_UI_ACHIEVEMENT_NEWSFEED	@"Achievement_NewsFeed"
#define ORIGIN_LAUNCH_URL_SOURCE_UI_SCORE_NEWSFEED	@"Score_NewsFeed"

#define DEFAULT_AVATAR_PICTURE	(@"default_avatar_40x40.png")
#define DEFAULT_PROFILE_AVATAR_PICTURE	(@"default_avatar.png")

#define RESULT_DICTIONARY_ERROR_STAGES_KEY @"errorStages"

#endif //_IPSP_CONSTANTS_H_
