#pragma once

#include "core.h"

enum GachaRewardCode
{
    GachaRewardCode_Gems                = 3008,
    GachaRewardCode_Coins               = 4013,
    GachaRewardCode_RMB					= 9999,
};

///
enum ErrorCode
{
    ErrorCode_FakeCopyProfile               = 301,
    ErrorCode_FakeProfileData               = 302,
    ErrorCode_FakeGemBetweenServer          = 201,
    ErrorCode_FakeCoinSign                  = 202,
    ErrorCode_FakeGemSign                   = 203,
    ErrorCode_FakeKeySign                   = 204,
    ErrorCode_FakePowerupSign               = 205,
    ErrorCode_FakePlantPieceSign            = 206,
    ErrorCode_FakeUnlockPlantSign           = 207,
    ErrorCode_FakeGameFeatureSign           = 208,
    ErrorCode_FakeWorldMapSign              = 209,
    ErrorCode_FakePurchaseSign              = 210,
    ErrorCode_FakeWorldKeysSign             = 211,
    ErrorCode_FakeAvatarPieceSign			= 212,
    ErrorCode_FakeUnlockedAvatarSign		= 213,
    ErrorCode_FakePlantStarLevelSign        = 214,
    ErrorCode_FakeICloudProfileSign			= 215,
    ErrorCode_FakeStoneSign                 = 216,
    ErrorCode_FakeAccessoryPieceSign        = 217,
    ErrorCode_FakeAccessoryInfoSign         = 218,
    ErrorCode_FakeRedPacketSign             = 219,
    ErrorCode_FakeLeafSign                  = 220,
    ErrorCode_FakePlantAwakenSign           = 221,
};
enum EConsoleContext
{
    CONSOLE_APP,
    CONSOLE_GAME_SELECTOR,
    CONSOLE_BOARD,
    CONSOLE_BOARD_SPAWN,
};
enum AdviceType
{
	ADVICE_NONE = -1,
    ADVICE_PLANT_FOOD_BANK_FULL,
	ADVICE_SEED_REFRESH,
	ADVICE_PLANT_GRAVEBUSTERS_ON_GRAVES,
	ADVICE_PLANT_NOT_ON_GRAVE,
	ADVICE_CANT_PLANT_THERE,
	ADVICE_PLANT_NOT_ON_WATER,
	ADVICE_PLANT_NOT_ON_RAIL,
	ADVICE_PLANTING_NEEDS_GROUND,
	ADVICE_HUGE_WAVE,
	NUM_ADVICE_TYPES
};
// THIS MUST MATCH UP WITH get_magento_files.py
// Also, change the look up where we set m_magentoLanguage if you add/remove one
enum MagentoLanguage
{
    MAGENTOLANGUAGE_Chinese = 0,
	MAGENTOLANGUAGE_English,
	MAGENTOLANGUAGE_German,
	MAGENTOLANGUAGE_French,
	MAGENTOLANGUAGE_Italian,
	MAGENTOLANGUAGE_Portuguese,
	MAGENTOLANGUAGE_Spanish,
	MAGENTOLANGUAGE_Count
};
enum GameFeature
{
	// You must add any new enums to GameFeatureType::StaticClassInit() if you want it
	// in your profile.
	//
	// GameFeatureType::ToString() has the enum to data string to mapping, which is REQUIRED
	// if you want the feature to be unlocked at a specific time.
	//
    // DO NOT CHANGE THE ORDER OR THESE FEATURES! ALL NEW FEATURES MUST GO
	// TO THE END OF THE LIST!
    //
	// Otherwise, it's ALWAYS unlocked
	// \/   \/   \/   \/   \/   \/   \/   \/   \/   \/   \/   \/   \/   \/   \/   \/
	FEATURE_SHOVEL = 0,
	FEATURE_ALMANAC = 1,
	FEATURE_COINS = 2,
	FEATURE_GEMS = 3,
    FEATURE_BUY_SUN = 4,
	FEATURE_KEYS = 5,
	FEATURE_WORLDMAP = 6,
	FEATURE_PLANTFOOD = 7,
	FEATURE_PLANTFOOD_PURCHASE = 8,
	FEATURE_HAS_PLAYED_DANGERROOM = 9,
	FEATURE_HAS_FAILED_DANGERROOM = 10,
	FEATURE_HAS_WON_DANGERROOM = 11,
	FEATURE_TREASURE_YETI = 12,
	FEATURE_UPGRADE_LAWNMOWER_TYPE_1 = 13,
	FEATURE_UPGRADE_LAWNMOWER_TYPE_2 = 14,
	FEATURE_UPGRADE_LAWNMOWER_TYPE_3 = 15,
	FEATURE_UPGRADE_6_SLOTS = 16,
	FEATURE_UPGRADE_7_SLOTS = 17,
	FEATURE_UPGRADE_8_SLOTS = 18,
	FEATURE_UPGRADE_SHOVEL_LVL1 = 19,
	FEATURE_UPGRADE_SHOVEL_LVL2 = 20,
	FEATURE_UPGRADE_SHOVEL_LVL3 = 21,
	FEATURE_UPGRADE_PF_REFRESH = 22,
	FEATURE_UPGRADE_WALLNUT_FIRSTAID = 23,
	FEATURE_UPGRADE_PF_SLOTS_LVL1 = 24,
	FEATURE_UPGRADE_PF_SLOTS_LVL2 = 25,//we never use this now
	FEATURE_UPGRADE_PF_SLOTS_LVL3 = 26,
	FEATURE_UPGRADE_STARTING_SUN_LVL1 = 27,
	FEATURE_UPGRADE_STARTING_SUN_LVL2 = 28,
	FEATURE_UPGRADE_STARTING_SUN_LVL3 = 29,
	FEATURE_POWERUP_WIZARDFINGER = 30,
	FEATURE_POWERUP_FLICKZOMBIE = 31,
	FEATURE_POWERUP_PINCH = 32,
    FEATURE_CHANGE_SPEED = 33,
    FEATURE_POWERUP_TACTICALCUKE = 34,
    FEATURE_CARD_KONGFU_COMING_SOON = 35,
    FEATURE_UPGRADE_SHOVEL_LVL4 = 36,
    FEATURE_UPGRADE_STARTING_SUN_LVL4 = 37,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_4 = 38,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_5 = 39,
    FEATURE_FESTIVAL_ENTRANCE = 40,
    FEATURE_FESTIVALGAME_CRAZYYETI_LEGEND = 41,
    FEATURE_FESTIVALGAME_GARGANTUARCRISIS_LEGEND = 42,
    FEATURE_FESTIVALGAME_DEVILINVADE_LEGEND = 43,
    FEATURE_KONGFU_SECOND_PART = 44,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_6 = 45,
    FEATURE_UPGRADE_MANUAL_MOWERS_1 = 46,
    FEATURE_UPGRADE_MANUAL_MOWERS_2 = 47,
    FEATURE_UPGRADE_MANUAL_MOWERS_3 = 48,
    FEATURE_UPGRADE_MANUAL_MOWERS_4 = 49,
    FEATURE_UPGRADE_MANUAL_MOWERS_5 = 50,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_7 = 51,
    FEATURE_FESTIVALGAME_WEALTHGOD_LEGEND = 52,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_8 = 53,
    FEATURE_TIP_FREEZINGWIND = 54,
    FEATURE_TIP_SHIELD = 55,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_9 = 56,
    FEATURE_AIR_MISSILE_GUIDE = 57,
    FEATURE_CANNON_1 = 58,
    FEATURE_SHIELD_1 = 59,
    FEATURE_CANNON_INTRO = 60,
    FEATURE_SHIELD_INTRO = 61,
    //For Plant Record
    FEATURE_BATTLE_ARRAY = 62,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_10 = 63,
    FEATURE_CHRISTMAS_PROTECT_INTRO = 64,
    FEATURE_UNLOCK_HARDLEVEL = 65,
    FEATURE_GET_EASYLEVEL_STAR = 66,    
    FEATURE_UPGRADE_LAWNMOWER_TYPE_11 = 67,
    
    FEATURE_UPGRADE_LAWNMOWER_TYPE_12 = 68,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_13 = 69,
    
    FEATURE_UPGRADE_LAWNMOWER_TYPE_14 = 71, // skip 70, it's used by old version and delete in new version
    FEATURE_UPGRADE_LAWNMOWER_TYPE_15 = 72,
    FEATURE_UPGRADE_LAWNMOWER_TYPE_16 = 73,

    FEATURE_POWERUP_VASEBREAKER_MOVE,
	FEATURE_POWERUP_VASEBREAKER_REVEAL,
	FEATURE_POWERUP_VASEBREAKER_COLOR,
	FEATURE_POWERUP_VASEBREAKER_BUTTER,

	FEATURE_HAS_SEEN_RIFT_HOW_TO_PLAY,
	FEATURE_COUNT,
};

enum GameBonus
{
    BONUS_GOLD_1,
    BONUS_GOLD_2,
    BONUS_GOLD_3,
    BONUS_DIAMOND_1,
    BONUS_DIAMOND_2,
    BONUS_DIAMOND_3,
    BONUS_GOLD_4,//add to the end
    
    //1
    BONUS_CARD_GOLD_250,
    BONUS_CARD_GOLD_500,
    BONUS_CARD_GOLD_1000,
    BONUS_CARD_GOLD_5000,
    
    BONUS_CARD_KEY_EGYPT,
    
    BONUS_CARD_DIAMOND_5,
    BONUS_CARD_DIAMOND_10,
    BONUS_CARD_DIAMOND_50,
    
    BONUS_CARD_PIECE_SNOWPEA,
    BONUS_CARD_PIECE_TORCHWOOD,
    
    BONUS_CARD_PIECE_PEAPOD,
    
    //2
    BONUS_CARD_PIECE_KERNELPULT,
    
    BONUS_CARD_PIECE_LIGHTNINGREED,
    BONUS_CARD_PIECE_COCONUTCANNON,
    
    BONUS_CARD_KEY_PIRATE,
    
    //3
    BONUS_CARD_PIECE_MELONPULT,
    BONUS_CARD_PIECE_IMITATER,
    
    BONUS_CARD_KEY_COWBOY,
    
    //4
    BONUS_CARD_PIECE_FIREGOURD,
    BONUS_CARD_PIECE_PEACH,
    
    BONUS_CARD_KEY_KONGFU,
    
    //5
    BONUS_CARD_PIECE_MAGNIFYINGGRASS,
    BONUS_CARD_PIECE_STARFRUIT,
    
    BONUS_CARD_KEY_FUTURE,
    
    
    BONUS_GOLD_5,
    BONUS_DIAMOND_4,
    
    BONUS_GOLD_6,
    BONUS_GOLD_7,
    BONUS_GOLD_8,
    BONUS_GOLD_9,
    BONUS_GOLD_10,
    BONUS_GOLD_11,
    BONUS_GOLD_12,
    BONUS_GOLD_13,
    BONUS_GOLD_14,
    BONUS_GOLD_15,
    BONUS_GOLD_16,
    BONUS_GOLD_17,
    BONUS_GOLD_18,
    
    BONUS_CARD_KEY_DARK,
    
    BONUS_CARD_KEY_BEACH,
    
    BONUS_CARD_KEY_ICEAGE,
    
    BONUS_MAGIC_FERTILIZER,
    BONUS_MAGIC_DRUM,
    BONUS_MAGIC_SNOWFLAKE,
    
    BONUS_MAGIC_TORCH,
    BONUS_MAGIC_REGENERATION,
    BONUS_MAGIC_POLE,
    
    BONUS_CARD_KEY_SKYCITY,
    
    BONUS_MAGIC_FERTILIZER_2,
    BONUS_MAGIC_POLE_2,
    
    BONUS_CARD_KEY_LOSTCITY,
    
    BONUS_COUNT
};

enum AdvicePriority
{
	ADVICE_PRIORITY_HIGH,			// Used for tutorials (always shown)
	ADVICE_PRIORITY_MEDIUM,			// Used for rare "higher" priority contextual stuff
	ADVICE_PRIORITY_LOW,			// Used for contextual stuff
	ADVICE_PRIORITY_NONE,
};
enum
{
	DIALOG_OPENURL_WAIT = 0,
	DIALOG_GAME_OVER,
	DIALOG_WORLD_MAP_PLANT_REWARD,
	DIALOG_INFO,
	DIALOG_MESSAGE,
	NUM_DIALOGS // keep last
};

enum StoreType {
	STORE_TYPE_COIN = 0,
	STORE_TYPE_SUN,
	STORE_TYPE_GEM,
    STORE_TYPE_STAMINA,
    STORE_TYPE_GACHA,
    STORE_TYPE_AVATAR,
    STORE_TYPE_LEAF,
    STORE_TYPE_STONE,
    STORE_TYPE_FUEL,
    STORE_TYPE_MYSTERY,
    STORE_TYPE_ZTICKET,
    STORE_TYPE_PVZ1MODE_TIME_ENERGY,
};
enum PurchaseType {
	PURCHASE_GEM = 0,
	PURCHASE_MONEY,
	PURCHASE_COIN,	
   	PURCHASE_LEAF,	
    PURCHASE_STONE,
    PURCHASE_AD
};
enum ProductBanner {
    PRODUCT_BANNER_NULL,
    PRODUCT_BANNER_HOT,
    PRODUCT_BANNER_DISCOUNT_30,
    PRODUCT_BANNER_DISCOUNT_50,
    PRODUCT_BANNER_DISCOUNT_70,
};

enum ICloud_FestivalGameMode
{
    //Notice the order should be strictly the same with FestivalGameMode.
    //e.g. ICloud_FestivalGameMode_CrazyYeti - FestivalGameMode_CrazyYeti = 10501, which equals ICloud_FestivalGameMode_None.
    //New game mode should follow this rule.
    ICloud_FestivalGameMode_None = 10501, //This is a start symbol, we only use its name to do some transform
    ICloud_FestivalGameMode_CrazyYeti = 10501,
    ICloud_FestivalGameMode_GargantuarCrisis,
    ICloud_FestivalGameMode_DevilInvade,
    ICloud_FestivalGameMode_WealthGod,
};

enum FestivalGameMode {
    FestivalGameMode_None=-1,
	//FestivalGameMode_CannonGame,
	FestivalGameMode_CrazyYeti,
	FestivalGameMode_GargantuarCrisis,
	FestivalGameMode_DevilInvade,
  	FestivalGameMode_WealthGod,
	FestivalGameMode_MiniGame,
    FestivalGameMode_Count
};

enum FestivalGameLevel {
	FestivalGameLevel_Medium,
	FestivalGameLevel_Hard,
    FestivalGameLevel_Legend,
    FestivalGameLevel_Count
};

enum FestivalGameReward {
    FestivalGameReward_Coin,
    FestivalGameReward_Gem,
	FestivalGameReward_Avatar,
    FestivalGameReward_Piece,
    FestivalGameReward_Count
};

enum BattleArrayType
{
    BattleArrayType_Default = -1,
    BattleArrayType_Normal,
    BattleArrayType_CrazyYeti,
    BattleArrayType_GargantuarCrisis,
    BattleArrayType_DevilInvade,
    BattleArrayType_DangerRoom,
    BattleArrayType_DangerRoom_Training
};

enum PlatformType {

	PLATFORM_NULL = 0,

	PLATFORM_CHINA_MOBILE,

	PLATFORM_CHINA_UNICOM,
	PLATFORM_CHINA_UNICOM_WIDEBAND,

	PLATFORM_CHINA_TELECOM,

	PLATFORM_CHINA_MOBILE_MM,

	PLATFORM_CHINA_MOBILE_HD,

	PLATFORM_CHINA_MOBILE_MM_SICHUAN_HD,

	PLATFORM_CHINA_UNICOM_HD,
	PLATFORM_CHINA_UNICOM_WIDEBAND_HD,
	PLATFORM_CHINA_UNICOM_YINGYETING_HD,


	PLATFORM_CHINA_MOBILE_MM_HD,


	PLATFORM_QQ,

	PLATFORM_QQ_HD,


	PLATFORM_THIRD_CHANNEL_START,

	PLATFORM_91,

	PLATFORM_BAIDU_DUOKU,

	PLATFORM_BAIDU_YOUXI,

	PLATFORM_BAIDU_IQIYI,

	PLATFORM_ANZHI,

	PLATFORM_UC,

	PLATFORM_WANDOULABS,

	PLATFORM_XIAOMI,

	PLATFORM_YINGYONGHUI,

	PLATFORM_XINLANG,

	PLATFORM_SHOUGOU,

	PLATFORM_DANGLE,

	PLATFORM_JINLI,

	PLATFORM_MAOPAOTANG,

	PLATFORM_360,

	PLATFORM_MUMAYI,

	PLATFORM_JINSHAN,

	PLATFORM_MOTO,

	PLATFORM_LENOVO,

	PLATFORM_ZHONGXING,

	PLATFORM_CHUANGWEI,

	PLATFORM_7K,

	PLATFORM_OPPO,

	PLATFORM_HUAWEI,

	PLATFORM_4399,

	PLATFORM_SUNING,

	PLATFORM_POPCAP,

	PLATFORM_LEWANYOU,

	PLATFORM_SHOUHU,
	PLATFORM_PPS,
	PLATFORM_AIQIYI,
	PLATFORM_YOUYI,
	PLATFORM_YOUKU,
	PLATFORM_NDUO,
	PLATFORM_TIANTIANDONGTING,
	PLATFORM_TIANYIDA,
	PLATFORM_BUBUGAO,
	PLATFORM_HANGZHOUMOPIN,
	PLATFORM_XUANCAIHUDONGMOPO,

	PLATFORM_TENCENT,

	PLATFORM_LESHI,
	PLATFORM_MEIZU,
    PLATFORM_KUPAI,

	PLATFORM_THIRD_CHANNEL_END,


	PLATFORM_TELECOM_CHANNEL_START,

	PLATFORM_TELECOM_KUPAI,

	PLATFORM_TELECOM_LENOVO,

	PLATFORM_TELECOM_HUAWEI,

	PLATFORM_TELECOM_ZHONGXING,

	PLATFORM_TELECOM_ZHONGXINGYOUXI,

	PLATFORM_TELECOM_CHANNEL_END,


	PLATFORM_THIRD_CHANNEL_HD_START,

	PLATFORM_91_HD,

	PLATFORM_BAIDU_DUOKU_HD,

	PLATFORM_BAIDU_YOUXI_HD,

	PLATFORM_BAIDU_IQIYI_HD,

	PLATFORM_ANZHI_HD,

	PLATFORM_UC_HD,

	PLATFORM_WANDOULABS_HD,

	PLATFORM_XIAOMI_HD,

	PLATFORM_YINGYONGHUI_HD,

	PLATFORM_XINLANG_HD,

	PLATFORM_SHOUGOU_HD,

	PLATFORM_DANGLE_HD,

	PLATFORM_JINLI_HD,

	PLATFORM_MAOPAOTANG_HD,

	PLATFORM_360_HD,

	PLATFORM_MUMAYI_HD,

	PLATFORM_JINSHAN_HD,

	PLATFORM_MOTO_HD,

	PLATFORM_LENOVO_HD,

	PLATFORM_ZHONGXING_HD,

	PLATFORM_CHUANGWEI_HD,

	PLATFORM_7K_HD,

	PLATFORM_OPPO_HD,

	PLATFORM_HUAWEI_HD,

	PLATFORM_4399_HD,

	PLATFORM_SUNING_HD,

	PLATFORM_POPCAP_HD,

	PLATFORM_LEWANYOU_HD,

	PLATFORM_SHOUHU_HD,
	PLATFORM_PPS_HD,
	PLATFORM_AIQIYI_HD,
	PLATFORM_YOUYI_HD,
	PLATFORM_YOUKU_HD,
	PLATFORM_NDUO_HD,
	PLATFORM_TIANTIANDONGTING_HD,
	PLATFORM_TIANYIDA_HD,
	PLATFORM_BUBUGAO_HD,
	PLATFORM_HANGZHOUMOPIN_HD,
	PLATFORM_HONGLONGGUO_HD,
	PLATFORM_ZHANGMENG_HD,
	PLATFORM_XUANCAIHUDONGMOPO_HD,

	PLATFORM_JJ_HD,
	PLATFORM_LESHI_HD,
	PLATFORM_PPZHUSHOU_HD,

	PLATFORM_MEIZU_HD,
    PLATFORM_KUPAI_HD,

	PLATFORM_TENCENT_HD,

	PLATFORM_PROTOTYPE_HD,

	PLATFORM_SAMSUNG_HD,

	PLATFORM_BAORUAN_HD,

	PLATFORM_PENGYOUWAN_HD,

	PLATFORM_NUBIYA_HD,

	PLATFORM_QIXIAZI_HD,

	PLATFORM_TIANTIAN_HD,

	PLATFORM_CHUIZI_HD,

	PLATFORM_KUBI_HD,

	PLATFORM_SHUMA_HD,

	PLATFORM_NIUKOU_HD,

	PLATFORM_WANKA_HD,

	PLATFORM_VR_HD,

	PLATFORM_PAPA_HD,

	PLATFORM_DEV_HD,

	PLATFORM_XYANDROID_HD,

	PLATFORM_QINGNING_HD,

	PLATFORM_DIANYOU_HD,

	PLATFORM_NEW_ZHONGXING_HD,

	PLATFORM_SHQC_HD,

	PLATFORM_2345_HD,

	PLATFORM_JINLIYU_HD,

	PLATFORM_DUOWANMC_HD,

	PLATFORM_YUEWAN_HD,

	PLATFORM_XIAOQI_HD,

	PLATFORM_CCYX_HD,

	PLATFORM_LEHIHI_HD,

	PLATFORM_QISHIZHUSHOU_HD,

	PLATFORM_XIXIRJY_HD,

	PLATFORM_BAIXUN_HD,

	PLATFORM_XIAOHA_HD,

	PLATFORM_DOUYIN_HD,

	PLATFORM_233QD_HD,

	PLATFORM_HAOYOUKB_HD,

	PLATFORM_BAIDU_GAME_HD,

	PLATFORM_KUAISHOU_HD,
	
	PLATFORM_NEW_PAPA_HD,
	
	PLATFORM_NEW_2345_HD,

	PLATFORM_NEW_MEITU_HD,

	PLATFORM_BYTEDANCE_HD,

	PLATFORM_SHARK_HD,
	
	PLATFORM_KS_HD,

	PLATFORM_BAZHANG_HD,

	PLATFORM_TODAYGAME_HD,

	PLATFORM_CCPLAY_HD,
	PLATFORM_QSZS_HD,
	PLATFORM_MIGU_HD,
	PLATFORM_MIGU4_HD,

	PLATFORM_MANGGUO_HD,
	PLATFORM_XIAOY_HD,

	PLATFORM_TEST_TW_HD,
	
	PLATFORM_CHINA_TELECOM_HD,

	PLATFORM_CHINA_TELECOM_MSQ_HD,

	PLATFORM_HBILI,

	PLATFORM_HOURPLAY,
	
	PLATFORM_BILIBILI_HD,

	PLATFORM_GONGHUI_HD,

	PLATFORM_TEST1_HD,
	PLATFORM_TEST2_HD,
	PLATFORM_TEST3_HD,
	PLATFORM_TEST4_HD,

	PLATFORM_KUAISHOUSHOU_HD,

	PLATFORM_HUAWEI_TV_HD,

	PLATFORM_HONOR_HD,

	PLATFORM_THIRD_CHANNEL_HD_END,


	PLATFORM_TELECOM_CHANNEL_HD_START,
	PLATFORM_TELECOM_AIYINYUE_HD,
	PLATFORM_TELECOM_ANHUIYITUO_HD,

	PLATFORM_TELECOM_KUPAI_HD,

	PLATFORM_TELECOM_LENOVO_HD,

	PLATFORM_TELECOM_HUAWEI_HD,

	PLATFORM_TELECOM_ZHONGXING_HD,

	PLATFORM_TELECOM_ZHONGXINGYOUXI_HD,
	PLATFORM_TELECOM_SUZHOURUIYI_HD,
	PLATFORM_TELECOM_GUANGDONGGUANGXIN_HD,
	PLATFORM_TELECOM_SICHUANSIFANG_HD,
	PLATFORM_TELECOM_WUHANCHAOWAN_HD,
	PLATFORM_TELECOM_GUANGZHOUDIANXIN_HD,
	PLATFORM_TELECOM_WUDIANSHIYE_HD,
	PLATFORM_TELECOM_SUZHOUKUYOU_HD,

	PLATFORM_TELECOM_CHANNEL_HD_END

};

enum IdType
{
    IdNone,
    IdPlant,
    IdPlantChip,
    IdAvatar,
    IdAvatarChip,
    IdAccessory,
    IdAccessoryChip,
    IdMaterial,
    IdGem,
    IdCoin,
};

enum ActiveEntranceType
{
    ActiveEntranceType_Main,
    ActiveEntranceType_Rebate,
    ActiveEntranceType_GoldEgg
};

enum GachaType
{
    GACHA_NORMAL,
    GACHA_RARE,
    GACHA_LEGEND,
	GACHA_AVATAR,
    GACHA_TYPE_COUNT
};

// this is for android version advertisement flag
enum AdvertisementType
{
	ADS_INVALID = -1,
	ADS_FREE_CHEST_GACHA,
	ADS_PLANT_ADVENTURE_SKIP,
	ADS_BATTLE_START,
	ADS_WORLD_SELECT,
	ADS_BATTLE_STATEMENT,
	ADS_CHALLENGE,
	ADS_DAILYSIGN,
	
	ADS_MAX,
};

// cheating check flag
enum CheatingCheckFlags
{
	PVZ_BEGIN_FLAG_ENUM(CHEATCHECK_),
	PVZ_FLAG(CHECK_DANGERROOM),
	PVZ_FLAG(CHECK_RIFTA),
	PVZ_FLAG(CHECK_BATTLE_Z),
	PVZ_END_FLAG_ENUM(CHEATCHECK_)
};
PVZ_MAKE_ENUM_BIT_OPERATORS(CheatingCheckFlags);
