#ifndef LEVEL_EDITOR_DEFINE_H
#define LEVEL_EDITOR_DEFINE_H


enum LevelEditorButton
{
    BTN_GROUND = 1,
    BTN_SURFACE,
    BTN_BOARD_STAGE,
    BTN_ZOMBIE_STAGE,

    BTN_LEVELNAME,
    BTN_CLOSE,
    BTN_BOARD_MODULE,
    BTN_ZOMBIE_MODULE,
    BTN_ENCOURAGE_SETTING,

    BTN_SUNMONEY,
    BTN_SUNMONEY_INPUT,
    BTN_PLANTFOOD,

    BTN_GROUND_SECE_SETTING,
    BTN_GROUND_PLANT_SETTING,
    BTN_SURFACE_SETTING,
    BTN_SUBTRACT,
    BTN_ADD,
    BTN_ZOMBIE_LEVEL_SET,
    BTN_ZOMBIE_PRESET_WAVES,
    BTN_ZOMBIE_CLEAR_WAVES,
    BTN_ZOMBIE_PLANTFOOD_SET,

    BTN_EVENT_STORM,
    BTN_EVENT_SPIDER_RAIN,
    BTN_EVENT_RAIDING_PARTY,
    BTN_EVENT_PORTAL,
    BTN_EVENT_DINO,
    BTN_EVENT_FROST_WIND,
    BTN_EVENT_PARACHUTE_RAIN,
    BTN_EVENT_BLACK_HOLE,

    BTN_CONFIRM,
    BTN_DISABLE_PLANT,
    BTN_EVIL_DAVE_SET_DISTANCE,
    BTN_EVIL_DAVE_SET_DISTANCE_ADD,
    BTN_EVIL_DAVE_SET_DISTANCE_SUBSTRACT,
    BTN_EVIL_DAVE_SET_DISTANCE_CONFIRM,

    BTN_VASE_BREAKER_SET_NUMBER,
    BTN_VASE_BREAKER_SET_NUMBER_CONFIRM = 1000,
    BTN_VASE_BREAKER_SET_NUMBER_MINUS,
    BTN_VASE_BREAKER_SET_NUMBER_ADD,

    BTN_DELETE,

};

enum LevelEditorCardType
{
    InvalidCard = 0,
    PlantCard,
    ZombieCard,
    GridItemCard,
    RailCard,
    MoldCard,
    TowerDefendRoad,
    PowerTileCard,
};


enum LevelEditorSeedBankType
{
    LevelEditor_Chooser,
	LevelEditor_Preset,
	LevelEditor_Conveyor,
};

#endif
