/*
 * WorldMapDefine.h
 *
 *  Created on: 2021-4-7
 *      Author: zhousen
 */

#ifndef WORLDMAPDEFINE_H_
#define WORLDMAPDEFINE_H_


enum HomeActityType
{
    HomeBossActivity = 0,
    HomeGachaActivity,
    HomeGiftBagActivity,
    HomePlantActivity,
    HomeDrawDollActivity,
    HomeDangerRoomActivity,
    HomeRedPacketActivity,
    HomeSpringShopActivity,
    HomeDinoCrisisActivity,
    HomePlantTreeActivity,
	HomeChildrenDayActivity,
    HomeChildrenDayActivity2018,
	HomeSummerEventActivity,
	HomeTimeTravelActivity,
	HomeModernWechatActivity,
	HomeNationalHolidayActivity,
	HomeMiniGameActivity,
	HomeDaveClubActivity,
	HomeActivityCount,
	HomeChrismasActivity,
	HomeFestivalActivity,
	HomePlantSpecialOfferActivity,
    HomeActivity_NationalBundle,
    HomeActivity_Worldcup,
    HomeFestivalDragonBoatActivity,
    HomeExpPlantActivity,
    HomeNationalDay2018Activity,
    HomeActivity_Joust,
    Home5thActivity,
    HomeActivity_WebGame,
    HomeLimitLottery,
    HomeRechargeBundle,
    HomeAnniversary,
    HomeWorldUnlockPack,
    HomeActivity_DailySignActivity,
    HomeActivity_NewYear_2018,
    HomeActivity_TravelLog,
    HomeActivity_NewerPresent,
    HomeActivity_DaveTreasure,
    HomeActivity_RechargeReward,
    HomeActivity_LuckBag,
    HomeActivity_DangerRoomSpecialOffer,
    HomeActivity_HappyVaseBreaker,
    HomeActivity_NewRecall,
    HomeActivity_SecretStore,
    HomeActivity_PlantAdventure,
    HomeActivity_PennyGuide,
    HomeActivity_AnniversaryTreasure,
    HomeActivity_MysteryStore,
    HomeActivity_MonthlyCardSpecial,
    HomeActivity_FightZodiac,
    HomeActivity_Levels,
    HomeActivity_PVP,
    HomeActivity_PennyPersuit,
    HomeActivity_StartConvert,
    HomeActivity_DaveShop,
    HomeActivity_Treasure,
    HomeActivity_FirstRecharge,
    HomeActivity_RechargeWelfare,
    HomeActivity_MonthlyCard,
    HomeActivity_LuckyLottery,
    HomeActivity_NoviceSevenDays,
    HomeActivity_ArtifactPresent,
    HomeActivity_PVZ1Mode,
    HomeActivity_CustomLevel,
    HomeActivity_PVPShop,
    HomeActivity_PennyClassroom,
    HomeActivity_SpecialEvent,
    HomeActivity_GrowthPackage,
    HomeActivity_UnchartedMode,
    HomeActivity_CardGame,
    HomeActivity_NewPVP,
    HomeActivity_BattleOrder,
    HomeActivity_Cornucopia,
    HomeActivity_Gene,
    HomeActivity_InvitationRewards,
    HomeActivity_GiftFoReturn,
};


#endif /* WORLDMAPDEFINE_H_ */
